blueprints/auth.py
from flask import Blueprint, render_template, jsonify, redirect, url_for, session,flash
from flask_login import current_user, logout_user, login_user, login_required
from exts import db
from flask_mail import Message
from flask_login import LoginManager
from flask import request
import datetime
import string
import random
#from models import EmailCaptchaModel
#from .forms import RegisterForm,LoginForm
from models import *
from werkzeug.security import generate_password_hash, check_password_hash

#blueprint是flask的子模块
#url_prefix 代表路由前缀
#cookie 中只适合少量的数据，一般用来存放登录授权的东西
#flask中的session，是经过加密后存储在cookie中的

bp=Blueprint("auth",__name__,url_prefix="/")
#定义时间格式
ISOTIMEFORMAT = '%Y-%m-%d %H:%M:%S'
#/grant/login
# @bp.route("/login")
# def login():
#     pass



@bp.route("/")
def index():
    return render_template("index.html")

@bp.route("/register",methods=['GET', 'POST'])
def register():
    if not current_user.is_anonymous:
        return redirect(url_for('auth.index'))
    if request.method == 'POST':
        userID = request.form.get('userID')
        password1 = request.form.get('password1')
        password2 = request.form.get('password2')
        if password1 != password2:
            flash('两次输入的密码不同')
            return redirect(url_for('auth.register'))
        staff = StaffModel.query.filter_by(id=userID).first()
        if staff is None:
            flash('员工号错误')
            return redirect(url_for('auth.register'))
        user = UserModel.query.filter_by(id=userID).first()
        if user is not None:
            flash('用户已注册')
            return redirect(url_for('auth.register'))

        user=UserModel(id=userID,password=password1)
        db.session.add(user)
        db.session.commit()
        flash('注册成功')
        return redirect(url_for('auth.index'))
    return render_template('register.html')

@bp.route("/login", methods=['GET', 'POST'])
def login():
    if request.method == 'GET':
        return render_template("login.html")
    else:
        userID = request.form.get('userID')
        password = request.form.get('password')

        if not userID or not password:
            flash('请输入')
            return redirect(url_for('auth.login'))

        staff = StaffModel.query.filter_by(id=userID).first()
        user = UserModel.query.filter_by(id=userID).first()
        if user is None:
            flash('员工号错误')
            return redirect(url_for('auth.login'))
        if not user.password==password:
            flash('密码错误')
            return redirect(url_for('auth.login'))
        flash('登录成功')
        login_user(staff)
        return redirect(url_for('auth.index'))
"""
    商店管理
    商店列表
    商店的增删改查
"""
@bp.route("/storelist", methods=['GET', 'POST'])
def storelist():
    if request.method == 'POST':
        info = request.form.get('info')
        date = request.form.get('date')
        if info == 'storeid':
            stores = StoreModel.query.filter_by(id=date).first()
            if stores is None:
                flash('该商店不存在')
                return redirect(url_for('auth.sotrelist'))
            return render_template('storelist.html', stores=stores, info=info)
        if info == 'storename':
            stores = StoreModel.query.filter_by(storename=date).first()
            if stores is None:
                flash('该商店不存在')
                return redirect(url_for('auth.storelist'))
            return render_template('storelist.html', stores=stores, info=info)

    stores =StoreModel.query.all()
    return render_template('storelist.html', stores=stores, info=1)

#后端采用<int:storeid>语法接受前端发送的storeid信息
@bp.route('/store_delete/<int:storeid>',methods=['POST'])
@login_required  # 登录保护
def store_delete(storeid):
    staff =StaffModel.query.filter_by(staffworkplace=storeid).first()
    if staff is not None:
        flash('该商店内存在员工 无法删除')
        return redirect(url_for('auth.storelist'))
    storgestore=StorgeStoreModel.query.filter_by(storgestoreid=storeid).first()
    request=RequestModel.query.filter_by(requeststoreid=storeid).first()
    sale=SaleModel.query.filter_by(salestoreid=storeid).first()
    if (storgestore is not  None) or (request is not None) or (sale is not  None):
        flash('仍存在关于该商店的记录 无法删除')
        return redirect(url_for('auth.storelist'))
    store=StoreModel.query.get_or_404(storeid)
    db.session.delete(store)
    db.session.commit()
    flash('删除成功')
    return redirect(url_for('auth.storelist'))

@bp.route('/store_alter/<int:storeid>',methods=['GET','POST'])
@login_required
def store_alter(storeid):
    store= StoreModel.query.get_or_404(storeid)
    if request.method == 'POST':
        storename = request.form.get('storename')
        storeplace= request.form.get('storeplace')
        store.storename = storename
        store.storeplace = storeplace
        db.session.commit()
        flash('更新成功')
        return redirect(url_for('auth.storelist'))

    return render_template('store_alter.html', store=store)


@bp.route('/store_add', methods=['GET', 'POST'])
@login_required
def store_add():
    if request.method == 'POST':
        storeid= request.form.get('storeid')
        storename = request.form.get('storename')
        storeplace = request.form.get('storeplace')
        store=StoreModel.query.filter_by(id=storeid).first()
        print(store)
        if store is None:
            store = StoreModel(id=storeid,storename=storename,storeplace=storeplace)
            db.session.add(store)
            db.session.commit()
            flash('添加成功')
            return redirect(url_for('auth.storelist'))
        else:
            flash('该商店已存在')
            return redirect(url_for('auth.storelist'))
    return render_template('store_add.html')

"""
    员工管理
    员工列表
    增删改查
"""
@bp.route("/stafflist", methods=['GET', 'POST'])
def stafflist():
    if request.method == 'POST':
        #info中存放查询的类型
        #date中存放查询的依据
        info = request.form.get('info')
        date = request.form.get('date')
        if info == 'staffid':
            staffs = StaffModel.query.filter_by(id=date).first()
            if staffs is None:
                flash('该员工不存在')
                return redirect(url_for('auth.stafflist'))
            return render_template('stafflist.html', staffs=staffs, info=info)
        if info == 'staffname':
            staffs = StaffModel.query.filter_by(staffname=date).first()
            if staffs is None:
                flash('该员工不存在')
                return redirect(url_for('auth.stafflist'))
            return render_template('stafflist.html', staffs=staffs, info=info)

    staffs = StaffModel.query.all()
    return render_template('stafflist.html', staffs=staffs, info=1)

@bp.route('/staff_delete/<int:staffid>',methods=['POST'])
@login_required  # 登录保护
def staff_delete(staffid):
    staff =StaffModel.query.filter_by(id=staffid).first()
    user=UserModel.query.filter_by(id=staffid).first()
    if user is not None:
        db.session.delete(user)
        db.session.commit()
    db.session.delete(staff)
    db.session.commit()
    flash('删除成功')
    return redirect(url_for('auth.stafflist'))

@bp.route('/staff_alter/<int:staffid>',methods=['GET','POST'])
@login_required
def staff_alter(staffid):
    staff= StaffModel.query.get_or_404(staffid)
    stores = StoreModel.query.all()
    if request.method == 'POST':
        staffsalary = request.form.get('staffsalary')
        staffworkplace= request.form.get('staffworkplace')
        staff.staffsalary = staffsalary
        staff.staffworkplace = staffworkplace
        db.session.commit()
        flash('更新成功')
        return redirect(url_for('auth.stafflist'))

    return render_template('staff_alter.html', staff=staff,stores=stores)


@bp.route('/staff_add', methods=['GET', 'POST'])
@login_required
def staff_add():
    if request.method == 'POST':
        staffid= request.form.get('staffid')
        staffname = request.form.get('staffname')
        stafftype=request.form.get('stafftype')
        staffsex=request.form.get('staffsex')
        staffsalary=request.form.get('staffsalary')
        staffworkplace = request.form.get('staffworkplace')
        active=1
        staff=StaffModel.query.filter_by(id=staffid).first()
        if staff is None:
            staff = StaffModel(id=staffid,staffname=staffname,stafftype=stafftype,staffsex=staffsex,staffsalary=staffsalary,staffworkplace=staffworkplace,active=active)
            db.session.add(staff)
            db.session.commit()
            flash('添加成功')
            return redirect(url_for('auth.stafflist'))
        else:
            flash('该员工已存在')
            return redirect(url_for('auth.stafflist'))
    stores = StoreModel.query.all()
    return render_template('staff_add.html',stores=stores)

@bp.route("/storgelist", methods=['GET', 'POST'])
def storgelist():
    if request.method == 'POST':
        #info中存放查询的类型
        #date中存放查询的依据
        info = request.form.get('info')
        date = request.form.get('date')
        if info == 'storgeid':
            storges = StorgeModel.query.filter_by(id=date).first()
            if storges is None:
                flash('该商品不存在')
                return redirect(url_for('auth.storgelist'))
            return render_template('storgelist.html', storges=storges, info=info)
    storges = StorgeModel.query.all()
    return render_template('storgelist.html', storges=storges, info=1)

@bp.route('/storge_add', methods=['GET', 'POST'])
@login_required
def storge_add():
    if request.method == 'POST':
        storgeid= request.form.get('storgeid')
        storgename = request.form.get('storgename')
        storgeproduce = request.form.get('storgeproduce')
        storgevalue = request.form.get('storgevalue')
        storgenumber = request.form.get('storgenumber')
        storge=StorgeModel.query.filter_by(id=storgeid).first()
        if storge is None:
            storge = StorgeModel(id=storgeid,storgename=storgename,storgeproduce=storgeproduce,storgevalue=storgevalue,storgenumber=storgenumber)

templates/base.html
<!DOCTYPE html>
<html lang="zh-CN">
<head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width,initial-scale=1.0">
        <title>连锁商店管理</title>
        <link rel="icon" href="{{ url_for('static',filename='favicon.ico') }}" >
		<link href="{{ url_for('static',filename='bootstrap.min.css') }}" rel="stylesheet">
		<link href="{{ url_for('static',filename='amaze.css') }}" rel="stylesheet" >
        <link href="{{ url_for('static',filename='style.css') }}" rel="stylesheet" >
        <style>
            .ti-widget,.ti-panel{
                font-style:normal;
            }
        </style>
        <script type="text/javascript" src="{{ url_for('static',filename='jquery-3.1.1.min.js') }}"></script>
        <script type="text/javascript" src="{{ url_for('static',filename='Chart.js') }}"></script>
        <script src="http://cdn.bootcss.com/jquery/1.11.0/jquery.min.js" ></script>
        <script src="{{ url_for('static',filename='jquery.table2excel.js') }}"></script>
        <script>
            $(document).ready(function () {
                var time = new Date();
                var day = ("0" + time.getDate()).slice(-2);
                var month = ("0" + (time.getMonth() + 1)).slice(-2);
                var today = time.getFullYear() + "-" + (month) + "-" + (day);
                $('#date_info_end').val(today);
            })
            $(document).ready(function () {
                var time = new Date();
                var day = ("0" + time.getDate()).slice(-2);
                var month = ("0" + (time.getMonth() + 1)).slice(-2);
                var today = time.getFullYear()-1 + "-" + (month) + "-" + (day);
                $('#date_info_start').val(today);
            })
        </script>
        <script>        $('input[required="required"]').before('<span style="color:red">*</span>');    </script>
{#        <link href="{{ url_for('static',filename='themify-icons.css') }}" rel="stylesheet" >#}

</head>
<body>
    {% for message in get_flashed_messages() %}
    <script rel="script">
        //弹出一个对话框
        alert("{{ message }}");
    </script>
{% endfor %}
{# 获取提示消息并显示 #}
{% block body %}
    
    <div class="wrapper" style="height: auto">
		<div class="sidebar" data-background-color="brown" data-active-color="danger">
	    <!--
			Tip 1: you can change the color of the sidebar's background using: data-background-color="white | brown"
			Tip 2: you can change the color of the active button using the data-active-color="primary | info | success | warning | danger"
		-->
			{% if current_user.is_authenticated %}
            <div class="logo">
                <a href="#" class="simple-text">
                    连锁商店管理
                </a>
            </div>
            {% else %}
			<div class="logo">
                <a href="#" class="simple-text">
                    请登录系统
                </a>
            </div>
			{% endif %}
            <div class="sidebar-wrapper">
				<ul class="nav">
                    <li>
                        <a href="{{ url_for('auth.index') }}">
                            <i class="ti-panel">&#9818</i>
                            <p>首页</p>
                        </a>
                    </li>
					{% if current_user.is_authenticated and current_user.stafftype=='管理员' %}
                        <li>
							<a href="{{ url_for('auth.storelist') }}">
								<i class="ti-widget">&#10001</i>
								<p>商店管理</p>
							</a>
						</li>
						<li>
							<a href="{{ url_for('auth.stafflist') }}">
								<i class="ti-widget">&#10001</i>
								<p>员工管理</p>
							</a>
						</li>
                        <li>
							<a href="{{ url_for('auth.storgelist') }}">
								<i class="ti-widget">&#10001</i>
								<p>库存管理</p>
							</a>
						</li>
                        <li>
							<a href="{{ url_for('auth.requestlist') }}">
								<i class="ti-widget">&#10001</i>
								<p>申请记录</p>
							</a>
						</li>
						  <li>
							<a href="{{ url_for('auth.deliverlist') }}">
								<i class="ti-widget">&#10001</i>
								<p>配送记录</p>
							</a>
						</li>
                        <li>
							<a href="{{ url_for('auth.salelist') }}">
								<i class="ti-widget">&#10001</i>
								<p>商店出货记录</p>
							</a>
						</li>
                    {% elif current_user.is_authenticated and current_user.stafftype=='商店经理' %}
					     <li>
							<a href="{{ url_for('auth.stafflist') }}">
								<i class="ti-widget">&#10001</i>
								<p>员工查看</p>
							</a>
						</li>
                         <li>
							<a href="{{ url_for('auth.storgelist') }}">
								<i class="ti-widget">&#10001</i>
								<p>配送申请</p>
							</a>
						</li>
                        <li>
							<a href="{{ url_for('auth.requestlist') }}">
								<i class="ti-widget">&#10001</i>
								<p>查看申请</p>
							</a>
						</li>
                        <li>
							<a href="{{ url_for('auth.storgestorelist') }}">
								<i class="ti-widget">&#10001</i>
								<p>查看库存</p>
							</a>
						</li>
						<li>
							<a href="{{ url_for('auth.deliverlist') }}">
								<i class="ti-widget">&#10001</i>
								<p>收货处理</p>
							</a>
						</li>
                         <li>
							<a href="{{ url_for('auth.salelist') }}">
								<i class="ti-widget">&#10001</i>
								<p>出货记录</p>
							</a>
						</li>
                     {% elif current_user.is_authenticated and current_user.stafftype=='售货员' %}
                        <li>
							<a href="{{ url_for('auth.storgestorelist') }}">
								<i class="ti-widget">&#10001</i>
								<p>出售货物</p>
							</a>
						</li>
                        <li>
							<a href="{{ url_for('auth.salelist') }}">
								<i class="ti-widget">&#10001</i>
								<p>出货记录</p>
							</a>
						</li>
					{% else %}
						<li>
							<a href="{{ url_for('auth.login') }}">
								<i class="ti-widget">&#9819</i>
								<p>登录</p>
							</a>
						</li>
						<li>
							<a href="{{ url_for('auth.register') }}">
								<i class="ti-widget">&#9812</i>
								<p>注册</p>
							</a>
						</li>
					{% endif %}


				</ul>

            </div>
        </div>

	<div class="main-panel">

            <nav class="navbar navbar-default">
                <div class="container-fluid">
                    <div class="navbar-header">
                        {% block title %}
                        <a class="navbar-brand" href="#"> Data-Table </a>
                        {% endblock %}
                    </div>
					{% if current_user.is_authenticated%}
					<div class="collapse navbar-collapse">
                        <ul class="nav navbar-nav navbar-right">
                            {% block write %}{% endblock %}
							<li>
                                <a href="{{ url_for('auth.logout') }}" class="btn btn-simple btn-info btn-icon like" data-toggle="dropdown">
                                    登出
                                </a>
                            </li>
						</ul>
					</div>
					{% endif %}
                </div>
            </nav>
            {% block div %}
            <div class="content">
            {% endblock %}
                <div class="container-fluid">
                    <div class="row">
                        <div class="col-md-12">
                            <div class="card">
							{% block content %}

							{% endblock %}
                                <!-- end content-->
                            </div>
                            <!--  end card  -->
                        </div>
                        <!-- end col-md-12 -->
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}
{% block login %}{% endblock %}
</body>
</html>

templates/login.html
{%  extends 'base.html' %}
{% block body %}{% endblock %}
{% block login %}
<div class="wrapper wrapper-full-page">
        <div class="full-page login-page"  data-color="blue">
            <!--   you can change the color of the filter page using: data-color="blue | purple | green | orange | red | rose " -->
            <div class="content">
                <div class="container">
                    <div class="row">
                        <div class="col-md-4 col-sm-6 col-md-offset-4 col-sm-offset-3">

                            <form method="post">
                                <div class="card card-login card-hidden">
                                    <div class="header text-center">
                                        <h3 class="title">登录</h3>
                                    </div>
                                    <div class="content">
                                        <div class="form-group">
                                            <label>员工号</label>
                                            <input type="text" name="userID" class="form-control input-no-border" autocomplete="off" required>
                                        </div>
                                        <div class="form-group">
                                            <label>密码</label>
                                            <input type="password" name="password" class="form-control input-no-border" autocomplete="off" required>
                                        </div>
                                    </div>
                                    <div class="text-center">
                                        <input type="submit" name="submit" class="btn btn-rose btn-wd btn-lg" value="登录">
                                        	<a href="{{ url_for('auth.register') }}">
                            					<i class="ti-id-badge">&#9998</i> 注册
                        					</a>

                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
{% endblock %}

templates/stafflist.html
{%  extends 'base.html' %}
{% block title %}
    <a class="navbar-brand" href="#"> 员工信息 </a>
{% endblock %}

{% block write %}
    {% if current_user.stafftype=='管理员' %}
    <li>
    <a href="{{ url_for('auth.staff_add') }}" class="btn btn-simple btn-info btn-icon like" data-toggle="dropdown">
        添加员工
    </a>
    </li>
    {% endif %}
{% endblock %}

{% block content %}
        <div class="content">
        <h4 class="title">员工信息</h4>
        <div class="toolbar">

            <!--        Here you can write extra buttons/actions for the toolbar              -->
            <form method="post">
                查询方式
                <select name="info" required>
                    <option value="staffid">员工编号</option>
                    <option value="staffname">员工姓名</option>
                </select>
                <input type="text" name="date" autocomplete="off" required>
                <input type="submit" name="submit" value="查询">
            </form>

        </div>
        {% if info == 'staffid' or info == 'staffname' %}
            <div class="material-datatables">
                <table id="datatables" class="table table-striped table-no-bordered table-hover"
                       style="width:100%;cellspacing:0">
                    <thead>
                    <tr>
						<th>员工编号</th>
                        <th>员工姓名</th>
                        <th>员工类型</th>
                        <th>员工性别</th>
                        <th>员工工资</th>
                         {% if current_user.stafftype=='管理员' %}
                        <th>工作商店编号</th>
                        <th>工作商店名称</th>
                        <th>工作商店地址</th>
                        <th class="disabled-sorting text-right">操作</th>
                        {% endif %}
                    </tr>
                    </thead>

                    <tbody>
                    <tr>
                        {% if current_user.stafftype=='管理员' %}
                            <td>{{ staffs.id }}</td>
                            <td>{{ staffs.staffname }}</td>
                            <td>{{ staffs.stafftype }}</td>
                            <td>{{ staffs.staffsex }}</td>
                            <td>{{ staffs.staffsalary }}</td>
                            <td>{{ staffs.staffworkplace }}</td>
                            <td>{{ staffs.storename.storename }}</td>
                            <td>{{ staffs.storename.storeplace }}</td>
                            <td class="text-right">
                                <form  method="post" action="{{ url_for('auth.staff_delete',staffid=staffs.id) }}">
                                    <a href="{{ url_for('auth.staff_alter',staffid=staffs.id) }}"
                                       class="btn btn-simple btn-info btn-icon like">修改</a>
                                    <input name="delete" type="submit" value="删除" onclick="return confirm('确认删除此员工？')" class="btn btn-simple btn-danger btn-icon remove">
                                </form>
                            </td>
                        {% elif  current_user.stafftype=='商店经理'%}
                            {% if current_user.staffworkplace==staffs.staffworkplace%}
                                <td>{{ staffs.id }}</td>
                                <td>{{ staffs.staffname }}</td>
                                <td>{{ staffs.stafftype }}</td>
                                <td>{{ staffs.staffsex }}</td>
                                <td>{{ staffs.staffsalary }}</td>
                            {% endif %}
                        {% endif %}
                    </tr>
                    </tbody>

                </table>
            </div>
        {% else %}

                <div class="material-datatables">
                    <table id="datatables" class="table table-striped table-no-bordered table-hover"
                           style="width:100%;cellspacing:0">
                        <thead>
                        <tr>
                            <th>员工编号</th>
                            <th>员工姓名</th>
                            <th>员工类型</th>
                            <th>员工性别</th>
                            <th>员工工资</th>
                            {% if current_user.stafftype=="管理员" %}
                            <th>工作商店编号</th>
                            <th>工作商店名称</th>
                            <th>工作商店地址</th>
                            <th class="disabled-sorting text-right">操作</th>
                            {% endif %}
                        </tr>
                        </thead>

                        <tbody>
                        {% if current_user.stafftype=="管理员" %}
                            {% for staff in staffs %}
                            <tr>
                               <td>{{ staff.id }}</td>
                                <td>{{ staff.staffname }}</td>
                                <td>{{ staff.stafftype }}</td>
                                <td>{{ staff.staffsex }}</td>
                                <td>{{ staff.staffsalary }}</td>
                                <td>{{ staff.staffworkplace }}</td>
                                <td>{{ staff.storename.storename }}</td>
                                <td>{{ staff.storename.storeplace }}</td>
                                <td class="text-right">
                                <form  method="post" action="{{ url_for('auth.staff_delete',staffid=staff.id) }}">
                                    <a href="{{ url_for('auth.staff_alter',staffid=staff.id) }}"
                                       class="btn btn-simple btn-info btn-icon like">修改</a>
                                    <input name="delete" type="submit" value="删除" onclick="return confirm('确认删除此员工？')" class="btn btn-simple btn-danger btn-icon remove">
                                </form>
                                </td>
                            </tr>
                            {% endfor %}
                        {% elif current_user.stafftype=="商店经理"%}
                            {% for staff in staffs %}
                            <tr>
                                {% if current_user.staffworkplace==staff.staffworkplace%}
                                   <td>{{ staff.id }}</td>
                                    <td>{{ staff.staffname }}</td>
                                    <td>{{ staff.stafftype }}</td>
                                    <td>{{ staff.staffsex }}</td>
                                    <td>{{ staff.staffsalary }}</td>
                                {% endif %}
                            </tr>
                            {% endfor %}
                        {% endif %}
                        </tbody>

                    </table>
                </div>


        {% endif %}
    </div>
{% endblock %}

templates/storelist.html
{%  extends 'base.html' %}
{% block title %}
    <a class="navbar-brand" href="#"> 商店信息 </a>
{% endblock %}

{% block write %}
    {% if current_user.stafftype=='管理员' %}
    <li>
    <a href="{{ url_for('auth.store_add') }}" class="btn btn-simple btn-info btn-icon like" data-toggle="dropdown">
        添加商店
    </a>
    </li>
    {% endif %}
{% endblock %}

{% block content %}
        <div class="content">
        <h4 class="title">商店信息</h4>
        <div class="toolbar">

            <!--        Here you can write extra buttons/actions for the toolbar              -->
            <form method="post">
                查询方式
                <select name="info" required>
                    <option value="storeid">商店编号</option>
                    <option value="storename">商店名称</option>
                </select>
                <input type="text" name="date" autocomplete="off" required>
                <input type="submit" name="submit" value="查询">
            </form>

        </div>
        {% if info == 'storeid' or info == 'storename' %}
            <div class="material-datatables">
                <table id="datatables" class="table table-striped table-no-bordered table-hover"
                       style="width:100%;cellspacing:0">
                    <thead>
                    <tr>
						<th>商店编号</th>
                        <th>商店名称</th>
                        <th>商店地址</th>
                        <th class="disabled-sorting text-right">操作</th>
                    </tr>
                    </thead>

                    <tbody>
                    <tr>
                        <td>{{ stores.id }}</td>
                        <td>{{ stores.storename }}</td>
                        <td>{{ stores.storeplace }}</td>


                        {% if current_user.satffype=='管理员' %}
                        <td class="text-right">
                            <form  method="post" action="{{ url_for('auth.store_delete',storeid=stores.id) }}">
                                <!-- 此处storeid=stores.id是将前端store.id传送给后端                           -->
                                <a href="{{ url_for('auth.store_alter',storeid=stores.id) }}"
                                   class="btn btn-simple btn-info btn-icon like">修改</a>
                                <input name="delete" type="submit" value="删除" onclick="return confirm('确认删除此商店？')" class="btn btn-simple btn-danger btn-icon remove">
                            </form>
                        </td>
                        {% endif %}
                    </tr>
                    </tbody>

                </table>
            </div>
        {% else %}

                <div class="material-datatables">
                    <table id="datatables" class="table table-striped table-no-bordered table-hover"
                           style="width:100%;cellspacing:0">
                        <thead>
                        <tr>
                            <th>商店编号</th>
                            <th>商店名称</th>
                            <th>商店地址</th>
                            <th class="disabled-sorting text-right">操作</th>
                        </tr>
                        </thead>

                        <tbody>
                        {% for store in stores %}
                        <tr>
                            <td>{{ store.id }}</td>
                            <td>{{ store.storename }}</td>
                            <td>{{ store.storeplace }}</td>

							{% if current_user.stafftype=="管理员" %}
                            <td class="text-right">
                            <form  method="post" action="{{ url_for('auth.store_delete',storeid=store.id) }}">
                                <a href="{{ url_for('auth.store_alter',storeid=store.id) }}"
                                   class="btn btn-simple btn-info btn-icon like">修改</a>
                                <input name="delete" type="submit" value="删除" onclick="return confirm('确认删除此商店？')" class="btn btn-simple btn-danger btn-icon remove">
                            </form>
                            </td>
							{% endif %}
                        </tr>
                        {% endfor %}
                        </tbody>

                    </table>
                </div>


        {% endif %}
    </div>
{% endblock %}